#!/bin/bash
#arr=(csvm0065 csvm0066 csvm0067)
arr=(mill002 mill004 mill006)
geometry=(109x24+10+40 80x24+1060+40 65x25+5-30 65x25+631-30 65x25+1258-30)
#command="java -jar -Djava.net.preferIPv4Stack=false workspace/mperf.jar -props HiTab.xml -mps 800 -mins 1"
#command="java -agentpath:/home/pg/p11/a7109534/yjp-12.0.6/bin/linux-x86-64/libyjpagent.so=monitors -jar workspace/mperf.jar -props Infinispan.xml -mps 100 -mins 1"
#command="java -Djava.net.preferIPv4Stack=true -agentpath:/home/pg/p11/a7109534/yjp-12.0.6/bin/linux-x86-64/libyjpagent.so=monitors -jar workspace/mperf.jar -props HiTab.xml -mps 800 -mins 1"
#command="java -Djava.net.preferIPv4Stack=true -agentpath:/home/pg/p11/a7109534/yjp-12.0.6/bin/linux-x86-64/libyjpagent.so=monitors -jar workspace/mperf.jar -props Infinispan.xml -mps 10 -mins 1"
#command="java -Djava.net.preferIPv4Stack=true -agentpath:/home/pg/p11/a7109534/yjp-12.0.6/bin/linux-x86-64/libyjpagent.so=monitors -jar workspace/mperf.jar -props decoupled_TOA_Box.xml"
#command="java -Djava.net.preferIPv4Stack=true -agentpath:/home/pg/p11/a7109534/yjp-12.0.6/bin/linux-x86-64/libyjpagent.so=monitors -jar workspace/mperf.jar -props toa_TCP.xml -anycastRequests true -control true"
createDir="mkdir -p /work/a7109534/; rm /work/a7109534/*"
config="toa.xml"
#config="decoupled_TOA_Box.xml"
#config="RMSysIntegrated.xml"
numberOfMessages="80000"
initiator=${arr[0]}
command="java -Djava.net.preferIPv4Stack=true -agentpath:/home/pg/p11/a7109534/yjp-2013-build-13072/bin/linux-x86-64/libyjpagent.so=monitors -jar workspace/mperf.jar -config $config -nr-messages $numberOfMessages -initiator $initiator"
for i in {0..3}; do
   gnome-terminal --geometry=${geometry[$i]} --title "${arr[$i]}" -x bash -c "ssh -t -o ConnectTimeout=1  a7109534@${arr[$i]}.ncl.ac.uk '$createDir; $command; bash'" > output.txt 2>&1
   sleep 0.5;
done
exit
